Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

  Subnet:
    Type: AWS::EC2::Subnet::Id

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id

  KeyName:
    Type: String

  IndexHTMLSource:
    Type: String

Resources:
  WebServerNetworkInterface:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId: !Ref Subnet
      GroupSet:
        - !Ref SecurityGroup
      SourceDestCheck: true
      Tags:
        - Key: Network
          Value: Web
        - Key: Name
          Value: !Sub ${EnvironmentName}-Private

  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0dc96254d5535925f
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - NetworkInterfaceId: !Ref WebServerNetworkInterface
          DeviceIndex: 0
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
          yum  -y install httpd
          curl ${IndexHTMLSource} -o /var/www/html/index.html
          service httpd start
          systemctl enable httpd
          sed -i -e 's/ZONE=".*"/ZONE="Australia\/Melbourne"/g' /etc/sysconfig/clock
          ln -sf /usr/share/zoneinfo/Australia/Melbourne /etc/localtime
          reboot
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-Web

Outputs:
  WebServerID:
    Value: !Ref WebServer
  PrimaryPrivateIpAddress:
    Value: !GetAtt WebServerNetworkInterface.PrimaryPrivateIpAddress
